name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      libsql-server-release:
        description: 'LibSQL Server Release'
        required: false
        default: 'libsql-server-v0.24.32'
        
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install sqld
      run: |
        curl --proto '=https' --tlsv1.2 -LsSf https://github.com/tursodatabase/libsql/releases/download/${{ github.event.inputs.libsql-server-release || 'libsql-server-v0.24.32' }}/libsql-server-installer.sh | sh
        echo "$HOME/.sqld/bin" >> $GITHUB_PATH
        sqld --version

    - name: Start sqld server
      run: |
        sqld &
        while ! curl -s http://localhost:8080/health > /dev/null; do
          echo "Waiting for sqld..."
          sleep 1
        done
        echo "sqld is ready!"

        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]
        
    - name: Run tests
      env:
        TURSO_DATABASE_URL: "localhost:8080"
        TURSO_AUTH_TOKEN: ""
      run: |
        pytest --cov=sqlalchemy_libsql tests/ 
